### ISSUE TITLE
File Garbage Collection

### ISSUE THREAD

**Issue by roryhofland** [ramp4-pcar4/storylines-editor#111]
When an image/chart/ramp config is removed from a slide via the editor, the link to the asset is removed from the Storyline config, but the associated file remains in it's folder. Would some sort of file garbage collection be desirable in this instance? This would prevent having unnecessary files pile up within the config file structure when creating/editing a Storyline product.

One immediate problem is that assets aren't unique, so if the same image was used in more than one place in the Storyline, deleting one would also affect the rest. This issue could be solved by assigning duplicate files some kind of uid, then storing them as separate files.

More trouble than its worth?

**Comment by spencerwahl** [comment]
> One immediate problem is that assets aren't unique, so if the same image was used in more than one place in the Storyline, deleting one would also affect the rest. This issue could be solved by assigning duplicate files some kind of uid, then storing them as separate files.

This was what I (tried) to do with the `sourceCounts` object, files are only removed if the last reference to it is being removed. I'm assuming that's not working as intended?

**Comment by roryhofland** [comment]
Maybe I'm misunderstanding how it's currently implemented, but when I save a config to the `server/public` folder with a deleted image, the unused file remains in the `assets` folder.

**Comment by RyanCoulsonCA** [comment]
This is actually something that probably has to be implemented on the server-side. The file is being properly removed from the ZIP file, but the server doesn't overwrite the entire folder (it just replaces the new files), so they aren't actually removed from the product.
