### ISSUE TITLE
Config changes to one map seem to save to every RAMP config when editing

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#124]
When modifying existing map files, and there are multiple maps in a product, saving changes to one seems to overwrite the config files for all other maps:
![image](https://user-images.githubusercontent.com/5294596/224557808-fc853ecb-c090-45ea-bda8-9ce1f3397801.png)

When you go back in to correct a config, the same behaviour occurs where all linked config files get overwritten with the same changes.

**Comment by mohsin-r** [comment]
This was recently fixed in #116.
Feel free to reopen this issue if things are still not working properly.
