### ISSUE TITLE
Make UUID known to editor

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#130]
If you create a new Storylines product using the Editor, the UUID or ID for the product should be known to the user beyond the landing page. The breadcrumb or some other wider variable can be used to advertise this value.

**Comment by RyanCoulsonCA** [comment]
Here's one proposal if we want it to be very visible to users, add it to the header under the product name:
![image](https://user-images.githubusercontent.com/25874602/224759827-45395d96-8db5-435c-b585-6d15448604ca.png)

Open to other ideas as well
