### ISSUE TITLE
Left/Right panel editting is "far away" from the ToC if a product has lots of slides

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#145]
I'm updating the Climate Action Map product with the editor, and noticed that if the ToC is very long because there is a lot of slides, the editing tools on the right need to be scrolled up to in order to access:
![image](https://user-images.githubusercontent.com/5294596/226694806-163baf14-d695-40c5-814c-969d0d5e0b3e.png)

![image](https://user-images.githubusercontent.com/5294596/226694925-694419de-6328-4d1b-8aa8-18dcda7c09a0.png)

This is not a "bug" per se, but it does create a bit of a navigation struggle when selecting slides low in the ToC for editing or review. Open to ideas on this one.

**Comment by yileifeng** [comment]
One option could be to use element `scrollIntoView` behavior.
