### ISSUE TITLE
Require French translations

### ISSUE THREAD

**Issue by yileifeng** [ramp4-pcar4/storylines-editor#202]
Ensure proper official French translations for all labels and titles across the editor for all pages marked in French. Some labels have no attempted unofficial translation such as `New Slide` or `Please select a slide to edit` on the slide editor page. 

Unofficial translation tool: https://portage-preprod.pwgsc.gc.ca/index-eng.php

**Comment by dan-bowerman** [comment]
If there is a spreadsheet or CSV of untranslated text, please provide it to me, I will send it for official translation.

**Comment by dan-bowerman** [comment]
Thanks for providing the CSV, Yi Lei! I will get these processed shortly.

**Comment by dan-bowerman** [comment]
Here are the translations: 

[10774979_001_FR_Text for Translation - 2023-05-26_Dan Bowerman.xlsx](https://github.com/ramp4-pcar4/storylines-editor/files/11721740/10774979_001_FR_Text.for.Translation.-.2023-05-26_Dan.Bowerman.xlsx)
