### ISSUE TITLE
Handling duplicate map/chart file names

### ISSUE THREAD

**Issue by mohsin-r** [ramp4-pcar4/storylines-editor#205]
When a user attempts to use the same file name when creating a map or chart, maybe we should at least display a warning that their already existing map/chart would be overwritten.

If we prefer to go with a more heavy handed approach (for lack of a better word), we could prevent the user from inputting duplicate file names or tag on a uuid or timestamp to the end of the file name to prevent duplication.

**Comment by dan-bowerman** [comment]
Let's go with the warning + overwrite approach.
