### ISSUE TITLE
Single-image slideshow issue

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#212]
Let me know if this is too much hassle to be worth it.

During the recent Testing Party, a few issues were logged that were the same underlying issue - single images were saved as slideshows with only one image in them, which added the inactive UI elements of the left and right paginator arrows. This is default Editor behaviour, it works well, but the "<" and ">" arrows seem to confuse users who are expecting to see more graphics. 

Maybe a checkbox or an "auto" setting of an image slideshow (or any type of slideshow) to force the image panel to simply be an image panel without a gallery/slideshow? e.g., if there is only one image present, make it an image panel; if there are more, make it a slideshow?.

**Comment by yileifeng** [comment]
See `slideshow-panel.vue` in this repo and port the changes over for a quick fix. 

Alternatively, a better solution might be to convert any single-image slideshows to an image panel before saving to the ZIP config. Would likely involve modifying the `saveChanges` method inside `image-editor` and would eliminate the dependence on the storylines viewer panel to detect for single-image slideshow panels.

**Comment by dan-bowerman** [comment]
Removing "High" priority - for the 9 products we recently pushed, we just manually changed these. We will want to revisit this when Editor development starts back up again.

**Comment by yileifeng** [comment]
Should have a temp fix when https://github.com/ramp4-pcar4/story-ramp/pull/358 is merged

**Comment by dan-bowerman** [comment]
Implicated in #225, we can probably close this one (needs further review).
