### ISSUE TITLE
Add French translations to metadata page

### ISSUE THREAD

**Issue by RyanCoulsonCA** [ramp4-pcar4/storylines-editor#215]
There is a bunch of text on the metadata page that doesn't update based on language, they're all just hard coded in. These should be added to the `lang.csv` file and French translations should be added for them.

These lines need to be added:
- `Storylines product details`
- `Fill in metadata details about your new Storyline. Use the “Preview” button to see what your slides will look like.`
- `Context link shows up at the bottom of the page to provide additional resources for interested users`
- `Context label shows up before the context link to explain what the link is for`

**Comment by yileifeng** [comment]
I included these in the spreadsheet sent for official translations in #202 so should be complete in same issue.

**Comment by dan-bowerman** [comment]
#202 has the attachment for the translations. Please get them in and feel free to close this issue once concluded.
