### ISSUE TITLE
Upgrade Vue CLI to Vite

### ISSUE THREAD

**Issue by yileifeng** [ramp4-pcar4/storylines-editor#238]
Same as https://github.com/ramp4-pcar4/story-ramp/issues/381

**Comment by mohsin-r** [comment]
Would like to mention that it may be worthwhile doing this now because we are using `vue-cli` version 4.xx. 
Because of this, I had to set the build target for the config editor to ES2015 which was quite a few years ago as using the newest version resulted in build errors.
