### ISSUE TITLE
Implement Help button and panel

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#264]
## Description

This issue is to implement a button in the RESPECT UI that will open a panel that serves Help documentation to the end user. 

### Is your feature request related to a problem?

Related Epic #255. 

## Proposed solution

The help documentation should be in a static location named after the language it is in (e.g. "respect-help-en.md", "respect-help-fr.md", etc), and its contents should display in the panel similar to RAMP3/RAMP4 with collapsible headings and a search box. 

## Alternatives considered
Open to ideas.

## Additional context

Where should this button go? 

## Related Issues

#263 - Create Markdown files

**Comment by yileifeng** [comment]
Reference work done in https://github.com/ramp4-pcar4/storylines-editor/pull/287 and pick up where this left off.
