### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by yileifeng** [ramp4-pcar4/storylines-editor#286]
## Description

Current README is a description of the Storylines viewer repo. Update this to include details on the editor. Include any link(s) to documentation or general guidelines on how to use the editor when possible.

**Comment by dan-bowerman** [comment]
-	Use Markdown format
-	Remove everything except the Project Setup section (these steps are still accurate)
-	Speak to how it is a merger of existing components: [RAMP4](https://github.com/ramp4-pcar4/ramp4-pcar4), [Storylines](https://github.com/ramp4-pcar4/story-ramp), [RAMP4 Config Editor](https://github.com/ramp4-pcar4/config-editor), [Highcharts Editor](https://www.highcharts.com/blog/products/highcharts-editor/)
-	This is a work in progress
-	Write a couple of explainer paragraphs about what the Editor is for
-	General usage documentation will come in the future
-	Provide a link to our [Marketing site](https://ramp4-pcar4.github.io/ramp-pcar/) and our generic email address: [applicationsdecartographieweb-webmappingapplications@ec.gc.ca](mailto:mapplicationsdecartographieweb-webmappingapplications@ec.gc.ca)
-	Include this blurb somewhere:
This is an unsupported product. If you require a supported version please contact [applicationsdecartographieweb-webmappingapplications@ec.gc.ca](mailto:applicationsdecartographieweb-webmappingapplications@ec.gc.ca) for a cost estimate. The software and code samples available on this website are provided "as is" without warranty of any kind, either express or implied. Use at your own risk. Access to this GitHub repository could become unavailable at any point in time.
-	Provide the markdown to the GitHub issue and we can make one of the devs ensure it gets committed in the next update.
