### ISSUE TITLE
French preview issues pt. 2

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#307]
## Description

Two issues attached to this that are likely related. Both I believe were started after the solution from https://github.com/ramp4-pcar4/storylines-editor/issues/305 was committed. 

- [x] 1. Cannot load the French Storylines configuration from the "Edit Existing" screen

- [x] 2. Cannot preview French Storylines products from the Editor

## Environment

- Any

## Screenshots
![image](https://github.com/ramp4-pcar4/storylines-editor/assets/5294596/9ac4f3b9-20fb-4b15-8d6e-a6e8afa77d79)

## Steps to reproduce
Part 1:

1. Load any Storylines product in the "Edit Existing Storylines Product" screen
2. Click "View French Config"
3. Click Next, the slides editor does not load at all. It will load if you refresh. 

Part 2: 

1. Load any Storylines product and enter the slide editing screen (e.g. https://intranet.dev.ncr.ec.gc.ca/Storylines-Editor-STB/index.html#/en/editor-main/55918bed-b04f-4d27-804b-7b62d44b77aa) 
2. Selected "View French Config"
3. Choose "Preview", a console error is thrown and nothing else happens. 

## Related issues

https://github.com/ramp4-pcar4/storylines-editor/issues/305

**Comment by RyanCoulsonCA** [comment]
I'll have a PR for the first issue shortly. The second one may take a bit longer as I can't reproduce it locally (can reproduce on the dev server though) and there aren't any errors showing up.

**Comment by RyanCoulsonCA** [comment]
PR to fix the first one is up now as well.
