### ISSUE TITLE
Non-traditional UUIDs are not loading as expected

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#324]
Found by Matt in 2024-06-18 Testing Party

## Description

Non traditional UUIDs are not loading as expected. For example, UUID "Matt - Testing Party" shows up in the list and was successfully saved to the server, however, it can't be loaded from the "Edit Existing Storylines Product" page. There appears to be a space at the end of the folder name on the server. Adding a space to the UUID field still doesn't work though.

## Steps to reproduce

1. Create a new storyline with a similar format to "Matt - Testing Party "
2. Save it
3. Return to the "Edit Existing Storylines Product" page
4. Try to load it

## Expected behavior

Storyline should load

## Possible solution

We're likely not trimming the UUID before sending the request to the server. 
Create rules around valid UUID inputs.

## Related issues

See the issue about nearly identical UUIDs (need a link)

**Comment by szczz** [comment]
#329
