### ISSUE TITLE
RAMP v4.5.0

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#326]
Found by James in 2024-06-18 Testing Party

## Description

v4.6.0 has a number of fixes. Also it looks like the Storylines repo is on an even older version of RAMP (from last October). Bit late to raise this I guess; kinda thing you'd want in before the big testing.

From Dan:
I'm a bit confused why this is the case; do our build processes not grab the latest version of RAMP and Storylines? Have we not integrated the npm packages for RAMP and Storylines? Or if we have, are the npm packages not being updated consistently?

**Comment by szczz** [comment]
>Have we not integrated the npm packages for RAMP and Storylines?

Yep, we're still dumping the built RAMP files into the public folder. We still need to integrate the npm package
