### ISSUE TITLE
ToC Editor

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#370]
## Description

We have options for a Table of Contents to be displayed in the collapsing left-hand navigation, or vertically at the top of the project. However, there currently exists no option for cleaning these options up or removing redundant entries. They are auto-generated, or need to be pruned via direct editing of the JSON.

### Is your feature request related to a problem?

This feature would allow users to modify the table of contents entries so something like this auto-generated horizontal ToC...
![image](https://github.com/user-attachments/assets/565d3bd5-0049-40b4-9ee3-862e8c82bbd7)

...could instead look neater and cleaner like this:
![image](https://github.com/user-attachments/assets/0963d4c1-c06c-4035-aa94-fb5a0d30c2f3)

## Proposed solution

Some sort of option to manipulate the Table of Contents options from within the RESPECT Editor.

## Alternatives considered

Alternatively, maybe each slide in the Editor has a checkbox, enabled by default... de-selecting this removes the slide from the ToC.

## Additional context

Consider also how this function may play out within a more unified English and French config editing experience. 

This feature would be useful for the TCEI project, but we are not limited to using the Editor for that project.

**Comment by yileifeng** [comment]
Address https://github.com/ramp4-pcar4/storylines-editor/issues/394 along with this
