### ISSUE TITLE
Investigate making text size configurable in the text editor

### ISSUE THREAD

**Issue by szczz** [ramp4-pcar4/storylines-editor#391]
## Description

We received some feedback from the clients regarding the ability to change the font size in text panels. 

>  It would be particularly useful to be able to choose and adjust the font size in the text section, as the current size seems a bit small for comfortable reading compared to our other web pages which are not in StoryRAMP format. 

Investigate the feasibility of introducing this feature. Was there a reason why this wasn't included in the original implementation?

**Comment by RyanCoulsonCA** [comment]
In yesterday's meeting for the TCEI & TMX products, @spencerwahl brought up the idea of having per-product CSS files which would make this pretty easy to do. We could also just add a new config option to do this.
