### ISSUE TITLE
Implement git based version history 

### ISSUE THREAD

**Issue by szczz** [ramp4-pcar4/storylines-editor#421]
## Description

Git has been shown respect on dev. This means we can finally get rid of the DB backups 🎉. This issue will be used to tackle the integration of git with Express Server, .NET API, and DB. 

# How this should work

1. When a new storyline is created, the Express API should init a new local repo in the folder of the storyline. An initial commit should be made. The commit hash should be returned to the Vue client and the Vue client relays this to the .NET API. The .NET API will then create a new VersionHistory record, along with a new Version record containing the commit hash. Update the Version entity to store a hash instead of the byte array.

2. When an existing storyline is saved, the Express API should commit the changes to the storyline to its existing local repo. This commit hash should be returned to the Vue client and the Vue client relays this to the .NET API. Create a new VersionHistory record, and create a new Version record containing the commit hash. The client should either fetch the user's profile again, or update the UserStore with the new commit.

3.  When the user selects a previous version (existing workflow, hash shouldn't be displayed just the date and time of the change) the hash is sent to a new endpoint in the Express API. The endpoint then cherrypicks the commit and returns the storyline at this version back to the client. 

Changes will need to be made to the .NET fetch endpoint to return the commit hashes to the frontend. Probably missing about 1000 edge cases here but we can expand this issue as we go.  

## Related Issues
#189

**Comment by mohsin-r** [comment]
We are making one change to the above design. The .NET API will no longer store version histories for products. Instead, version histories will be returned from the Express Server itself via the use of `git log`. The updated workflows are as follows:

1. When a new storyline is created, the Express API should init a new local repo in the folder of the storyline. An initial commit should be made.
2. When an existing storyline is saved, the Express API should commit the changes to the storyline to its existing local repo.  The client should update the `UserStore` with the new commit.
3. When the user selects a previous version (existing workflow, hash shouldn't be displayed just the date and time of the change) the hash is sent to a new endpoint in the Express API. The endpoint then cherrypicks the commit and returns the storyline at this version back to the client.
