### ISSUE TITLE
Adding <style> to text editor markdown affects page UI

### ISSUE THREAD

**Issue by gordlin** [ramp4-pcar4/storylines-editor#423]
## Description

Adding a <style> element inside the text editor will affect the CSS of the storylines editor page.

## Screenshots

<img width="1848" alt="image" src="https://github.com/user-attachments/assets/da2922f9-1142-4531-8218-950c318e8882">

## Steps to reproduce

1. Go to 00000000-0000-0000-0000-000000000000
2. In any text editor, paste the following:
```
<style>
body {
    font-size: 48px;
}
</style>
```

3. Witness the font size for the storylines editor increase to 48px.
## Expected behavior

UI font size should not change.

## Actual behavior

UI font size changes. User may get jumpscared.

**Comment by yileifeng** [comment]
This one might need to marinate from Spencer's comment https://github.com/ramp4-pcar4/storylines-editor/pull/429#pullrequestreview-2479909109
