### ISSUE TITLE
Previous version container has too large of a shadow

### ISSUE THREAD

**Issue by RyanCoulsonCA** [ramp4-pcar4/storylines-editor#434]
## Description

When viewing the list of previous product versions, the shadow is quite a bit larger than the container.

## Environment

- Browser (if applicable): Chrome

## Screenshots

![image](https://github.com/user-attachments/assets/ecbbde06-6871-4494-a841-4144be7ce782)

## Steps to reproduce

1. Load a product.
2. Click the `Show previous versions of product` button.
3. Notice that the shadow is larger than the container.

## Expected behavior

The shadow should wrap the container nicely.

## Actual behavior

The shadow is not wrapping the container nicely.

**Comment by IshavSohal** [comment]
Noticed this as well. Changing [this](https://github.com/ramp4-pcar4/storylines-editor/blob/6ab1b8b226789ecaec540bf983904c256a145569/src/components/metadata-editor.vue#L326C40-L326C57) from `span="2"` to `span="1"` should fix it.
