### ISSUE TITLE
Schema error on dynamic panel 

### ISSUE THREAD

**Issue by yileifeng** [ramp4-pcar4/storylines-editor#456]
## Description

Create a dynamic panel and make a non-empty image panel. The schema validation breaks on the advanced editor.

## Steps to reproduce

1. Make a new slide with a dynamic panel
2. Create an image panel and upload an image
3. Go to advanced editor and see error from schema validation mismatch

**Comment by RyanCoulsonCA** [comment]
Also getting a schema validation error when working with a fully populated dynamic panel. Removing the `modified` property from the dynamic panel config seems to fix it. We should add it to the schema to prevent this error from occurring.
