### ISSUE TITLE
Clarity on video content editor

### ISSUE THREAD

**Issue by james-rae** [ramp4-pcar4/storylines-editor#458]
## Description

Slide editor, choosing `video` as the content type, you get the second option

> or Paste the URL to a video

So I said "cool" and put a YouTube url in there. Didn't work. Tried again and clicked `Upload`. This made an empty zero-length video player appear.

### Is your feature request related to a problem?

Not saying it should support YouTube, but I was sorta hoping it would and it's not clear that it didn't.

## Proposed solution

- Some additional wording around that the URL should be / what is supported

## Additional context

![image](https://github.com/user-attachments/assets/88801c32-7ef2-4dd2-bdd1-ca5935d0bc7d)

**Comment by RyanCoulsonCA** [comment]
It does support YouTube, but I think it may only work with non-shortened URLs [https://www.youtube.com/watch?v=YQX7JYQjDOQ](https://www.youtube.com/watch?v=dQw4w9WgXcQ). Could be a good enhancement to support the shortened links, or I agree that we can add additional wording to clarify this

**Comment by james-rae** [comment]
Yeah if its just a template-matching issue then givver!
(I clicked your link fully expecting something and was not disappointed 🏆 )

**Comment by szczz** [comment]
>Could be a good enhancement to support the shortened links

Makes sense to me. Proceed with supporting shortened links
