### ISSUE TITLE
Unable to exit help modal using keyboard

### ISSUE THREAD

**Issue by IshavSohal** [ramp4-pcar4/storylines-editor#460]
## Description

Cannot exit the help modal using keyboard alone. Need to click away using mouse. 

## Steps to reproduce

1. Load a product into `editor-main`
2. Press Tab until you reach the Help button
3. Press Enter
4. Try to exit using keyboard alone

## Possible solution

Create an `x` button to close the modal

**Comment by szczz** [comment]
Can't reproduce. Esc key closes the modal in Firefox Version 133.0

Also works in Edge and Chrome

**Comment by IshavSohal** [comment]
Good catch, never considered esc for some reason lol. We can just close this issue then
