### ISSUE TITLE
Images need to save to assets/{lang}/

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#50]
Whenever I try to save an image (drag and drop into browser), I receive the following error in the server console:
	Validation of assets/en/NPRIpictogramme-2016data-EN.jpg failed. Deleting.

![NPRIpictogramme-2016data-EN](https://user-images.githubusercontent.com/5294596/214293436-a19c55d1-bc23-4bae-bcf1-310c5baa38a3.jpg)

**Comment by RyanCoulsonCA** [comment]
There's a security feature in the upload server code to ensure that file names match a certain regex. I forgot to allow capital letters in there, which is why that message is logged. I'm going to update this regex to reject "/" and "\" characters, but allow everything else.

**Comment by dan-bowerman** [comment]
Duplicate #4
