### ISSUE TITLE
Provide feedback when a button is selected

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#52]
Clicking most buttons does not seem to do anything at the moment. However, buttons that do work, e.g. clicking "Save" does actually attempt to save the Storylines product to the server, but there is no feedback for the user to know that anything has happened.

**Comment by yileifeng** [comment]
Also good to add a nicer way for user confirmation before proceeding with specific buttons (that may lose unsaved data) such as transitioning between page views, changing slide type, deleting slides, etc.
