### ISSUE TITLE
Load/Edit remote Storylines products

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#54]
We spoke about this a bit in a previous meeting, but I think this is going to be crucial to the longterm function of this application.

We need to be able to load and edit existing apps. As of this writing, you can save once and that's it. That isn't how anyone is going to use this application - most users will start with something barebones, save it, and go back to edit it multiple times. Some users will want to edit older Storylines products.

One idea (maybe it's bad), pull the Storylines_ID and scrape its main JSON file for slide details, URLs, etc. Maybe this all needs to be pulled locally for editing and then pushed back to the server (overwriting what's already there).

**Comment by dan-bowerman** [comment]
Related #55...

Section917 QC server is currently listening on port 6040

Contents get dumped in the following format:
https://section917.canadacentral.cloudapp.azure.com/respect/public/index-ca-en.html#/en/test

**Comment by RyanCoulsonCA** [comment]
I'm going to write up a proposal for this (as well as how we can normalize file saving since different panel types use different saving methods at the moment) and I'll post it here as soon as I'm finished with it.

**Comment by RyanCoulsonCA** [comment]
I've posted a discussion [here](https://github.com/ramp4-pcar4/storylines-editor/discussions/60)
