### ISSUE TITLE
Copy slides between languages

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#70]
Related #8 and #69 (nice) 

It would be very useful to an editor to be able to copy their English slide to French (or vice versa) for modification, instead of creating it again from scratch. This task is to facilitate the copying of slides between the two language configs and folders.

**Comment by dan-bowerman** [comment]
Blocked by #69 (nice)

**Comment by spencerwahl** [comment]
Ended up doing this at the same time as #69 but forgot to update the status of this one
