### ISSUE TITLE
Auto-generate UUIDs

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#73]
It would be nice if the user had a pre-generated UUID populating the UUID field for a new Storylines product. I've used this site in the past: https://www.uuidgenerator.net/, and Google even seems to generate one for you as well if you google "generate uuid". I would imagine there are countless libraries out there that can accomplish this.

**Comment by RyanCoulsonCA** [comment]
Just quickly searching, [this library](https://www.npmjs.com/package/uuid) could work.
