### ISSUE TITLE
Too easy to "leave" the page and eliminate all unsaved work

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#92]
If you click a link within the editor tab (e.g. any header or footer links from the Canada.ca template), it will take you to a new page, thus clearing all unsaved work. Suggest a prompt warning the user and giving them the option to cancel navigation. 
In a future phase we may consider having an auto-save option?

**Comment by RyanCoulsonCA** [comment]
Maybe this can go with https://github.com/ramp4-pcar4/storylines-editor/issues/88? If the `unchanged changes` indicator is being displayed, we can also display an alert before they leave the page reminding them that they have unsaved changes.
