### ISSUE TITLE
Map configuration - default to Lambert?

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#93]
I'm not clear how much flexibility we have with regards to the FGPA authoring tool and modifications.
The "defaults" are underwhelming: Projections are in Mercator and the default basemaps are Esri-hosted. At a minimum, we would like to have a Lambert Conformal Conic (LCC) projection by default, and the NRCan-hosted basemaps featured in all of our applications. 
Working with these Mercator defaults, I cannot get any data to display. 
Are we able to modify the FGPA to include/replace these?

**Comment by RyanCoulsonCA** [comment]
The default map config for the FGPA authoring tool can be modified without any modifications to the tool itself. [The file](https://github.com/ramp4-pcar4/storylines-editor/blob/main/public/scripts/ramp-editor/samples/config-default.json) is called `config-default.json` and is located under `public/scripts/ramp-editor/samples/`.

**Comment by dan-bowerman** [comment]
@dan-bowerman to post an "ideal" config.

**Comment by dan-bowerman** [comment]
@RyanCoulsonCA, attached is a zip of English and French "universal defaults". If we can plug as much of this into the FPGA tool, it will go a really long way to making map construction simple (in many cases users would just need to drop in a URL and a few labels). 
[map_default_configs.zip](https://github.com/ramp4-pcar4/storylines-editor/files/10803890/map_default_configs.zip)

**Comment by RyanCoulsonCA** [comment]
Done! Changes are in [PR now](https://github.com/ramp4-pcar4/storylines-editor/pull/105).
