### ISSUE TITLE
Back to Home link

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#94]
A "Back to Home" link that takes you to the landing page (Create/Edit Storylines Product) would be useful. 

I am open to suggestions on where this could go. Right now, you must use the browser back button or change the URL manually.

**Comment by yileifeng** [comment]
Related to #89

**Comment by RyanCoulsonCA** [comment]
I'm looking for some feedback for how we might want to add this back button. I've included some options below and I'd love to hear what everyone thinks. 

### Option 1
We add a second row below the edit metadata button to return to the landing page.

![](https://i.gyazo.com/a6f3b472698cb80ae83a8991ee9783d4.png)


### Option 2
We add another button to the top of the page. We have quite a bit going on up there already, so maybe we don't want it here.
![](https://i.gyazo.com/14ee611c57aab74e33bdf8d6393cbb23.png)

### Option 3
Add a little exit icon to the left of the product name at the top.
![](https://i.gyazo.com/d9108d771b14d09e95c353911a13c244.png)

Let me know what you think, or if you have any other suggestions!

**Comment by yileifeng** [comment]
Option 3 > Option 1 > Option 2 for me. Would just prefer to avoid over cluttering the right header section since the back button is not directly related to the current product like the other functions are.

**Comment by RyanCoulsonCA** [comment]
> Option 3 > Option 1 > Option 2 for me. Would just prefer to avoid over cluttering the right header section since the back button is not directly related to the current product like the other functions are.

👍 these are my preferences too
